"""added thumbnail to version

Revision ID: 0b9e5af4b889
Revises: 3f2fadbb17f2
Create Date: 2025-11-24 12:27:54.191212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b9e5af4b889'
down_revision: Union[str, Sequence[str], None] = '3f2fadbb17f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('thumbnail_path', sa.Text(), nullable=True))
    op.add_column('versions', sa.Column('thumbnail_ext', sa.String(), nullable=True))
    op.add_column('versions', sa.Column('thumbnail_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('versions', 'playblast_ext')
    op.drop_column('versions', 'playblast_path')
    op.drop_column('versions', 'playblast_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('playblast_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('versions', sa.Column('playblast_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('versions', sa.Column('playblast_ext', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('versions', 'thumbnail_metadata')
    op.drop_column('versions', 'thumbnail_ext')
    op.drop_column('versions', 'thumbnail_path')
    # ### end Alembic commands ###
