"""Added access group and project members

Revision ID: 15e1eee71a0d
Revises: 4b46e8707641
Create Date: 2025-12-15 14:51:53.480230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e1eee71a0d'
down_revision: Union[str, Sequence[str], None] = '4b46e8707641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_group_members', sa.Column('user_kc_id', sa.String(), nullable=False))
    op.create_unique_constraint('uq_access_group_members_user_access_group', 'access_group_members', ['user_kc_id', 'access_group_id'])
    op.drop_constraint(op.f('access_group_members_user_id_fkey'), 'access_group_members', type_='foreignkey')
    op.drop_column('access_group_members', 'user_id')
    op.drop_column('access_group_members', 'role')
    op.add_column('access_groups', sa.Column('kc_group_id', sa.String(), nullable=True))
    op.add_column('access_groups', sa.Column('kc_group_path', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'access_groups', ['kc_group_id'])
    op.drop_constraint(op.f('uq_project_group'), 'project_access_groups', type_='unique')
    op.drop_column('project_access_groups', 'id')
    op.add_column('user_project_roles', sa.Column('user_kc_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('uq_user_project_role'), 'user_project_roles', type_='unique')
    op.create_index('ix_user_project_roles_project_id', 'user_project_roles', ['project_id'], unique=False)
    op.create_index('ix_user_project_roles_user_kc_id', 'user_project_roles', ['user_kc_id'], unique=False)
    op.create_unique_constraint('uq_user_project', 'user_project_roles', ['project_id', 'user_kc_id'])
    op.drop_constraint(op.f('user_project_roles_user_id_fkey'), 'user_project_roles', type_='foreignkey')
    op.drop_column('user_project_roles', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_project_roles', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('user_project_roles_user_id_fkey'), 'user_project_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_project', 'user_project_roles', type_='unique')
    op.drop_index('ix_user_project_roles_user_kc_id', table_name='user_project_roles')
    op.drop_index('ix_user_project_roles_project_id', table_name='user_project_roles')
    op.create_unique_constraint(op.f('uq_user_project_role'), 'user_project_roles', ['project_id', 'user_id', 'role'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_project_roles', 'user_kc_id')
    op.add_column('project_access_groups', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_project_group'), 'project_access_groups', ['project_id', 'access_group_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'access_groups', type_='unique')
    op.drop_column('access_groups', 'kc_group_path')
    op.drop_column('access_groups', 'kc_group_id')
    op.add_column('access_group_members', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('access_group_members', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('access_group_members_user_id_fkey'), 'access_group_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_group', 'access_group_members', type_='unique')
    op.drop_column('access_group_members', 'user_kc_id')
    # ### end Alembic commands ###
