"""Updated user project table name

Revision ID: 1ad9d07b93d0
Revises: 15e1eee71a0d
Create Date: 2025-12-15 14:59:05.623682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ad9d07b93d0'
down_revision: Union[str, Sequence[str], None] = '15e1eee71a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_kc_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_kc_id', name='uq_user_projects')
    )
    op.create_index('ix_user_project_project_id', 'user_project', ['project_id'], unique=False)
    op.create_index('ix_user_project_user_kc_id', 'user_project', ['user_kc_id'], unique=False)
    op.drop_index(op.f('ix_user_project_roles_project_id'), table_name='user_project_roles')
    op.drop_index(op.f('ix_user_project_roles_user_kc_id'), table_name='user_project_roles')
    op.drop_table('user_project_roles')
    op.drop_constraint(op.f('uq_access_group_members_user_access_group'), 'access_group_members', type_='unique')
    op.create_unique_constraint('uq_user_groups', 'access_group_members', ['user_kc_id', 'access_group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_groups', 'access_group_members', type_='unique')
    op.create_unique_constraint(op.f('uq_access_group_members_user_access_group'), 'access_group_members', ['user_kc_id', 'access_group_id'], postgresql_nulls_not_distinct=False)
    op.create_table('user_project_roles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_kc_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('user_project_roles_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_project_roles_pkey')),
    sa.UniqueConstraint('project_id', 'user_kc_id', name=op.f('uq_user_projects'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_project_roles_user_kc_id'), 'user_project_roles', ['user_kc_id'], unique=False)
    op.create_index(op.f('ix_user_project_roles_project_id'), 'user_project_roles', ['project_id'], unique=False)
    op.drop_index('ix_user_project_user_kc_id', table_name='user_project')
    op.drop_index('ix_user_project_project_id', table_name='user_project')
    op.drop_table('user_project')
    # ### end Alembic commands ###
