"""updated versions schema

Revision ID: 3f2fadbb17f2
Revises: 19a4d81b6a40
Create Date: 2025-11-21 18:52:53.669957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f2fadbb17f2'
down_revision: Union[str, Sequence[str], None] = '19a4d81b6a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('representations')
    op.drop_table('import_assets_bb3')
    op.drop_index(op.f('uq_asset_type_name'), table_name='asset_types')
    op.alter_column('assets', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.add_column('versions', sa.Column('path', sa.Text(), nullable=False))
    op.add_column('versions', sa.Column('ext', sa.String(), nullable=False))
    op.add_column('versions', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('versions', sa.Column('playblast_path', sa.Text(), nullable=True))
    op.add_column('versions', sa.Column('playblast_ext', sa.String(), nullable=True))
    op.add_column('versions', sa.Column('playblast_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('versions', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('versions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('versions', 'tags')
    op.drop_column('versions', 'playblast_metadata')
    op.drop_column('versions', 'playblast_ext')
    op.drop_column('versions', 'playblast_path')
    op.drop_column('versions', 'meta')
    op.drop_column('versions', 'ext')
    op.drop_column('versions', 'path')
    op.alter_column('projects', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('assets', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('uq_asset_type_name'), 'asset_types', ['name'], unique=True)
    op.create_table('import_assets_bb3',
    sa.Column('sg_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mvl_client_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('client_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thumbnail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MVL Client Name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Client Name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Asset Name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('column11', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('representations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ext', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('thumbnail_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_ext', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_size_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_boxes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], name=op.f('representations_version_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('representations_pkey'))
    )
    # ### end Alembic commands ###
