"""add thumbnail fields

Revision ID: 40a732f68a0a
Revises: f44611b15651
Create Date: 2025-11-19 17:26:21.963645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40a732f68a0a'
down_revision: Union[str, Sequence[str], None] = 'f44611b15651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('representations', sa.Column('thumbnail_path', sa.Text(), nullable=True))
    op.add_column('representations', sa.Column('thumbnail_ext', sa.String(), nullable=True))
    op.add_column('representations', sa.Column('thumbnail_size_bytes', sa.BigInteger(), nullable=True))
    op.add_column('representations', sa.Column('thumbnail_boxes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('representations', 'thumbnail_boxes')
    op.drop_column('representations', 'thumbnail_size_bytes')
    op.drop_column('representations', 'thumbnail_ext')
    op.drop_column('representations', 'thumbnail_path')
    # ### end Alembic commands ###
