"""Added default thumbnail fields to asset_type and categories

Revision ID: 4b46e8707641
Revises: d5cdcd3ad71b
Create Date: 2025-12-04 13:12:05.904744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b46e8707641'
down_revision: Union[str, Sequence[str], None] = 'd5cdcd3ad71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_categories', sa.Column('default_thumbnail_path', sa.String(), nullable=True))
    op.add_column('asset_types', sa.Column('default_thumbnail_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_types', 'default_thumbnail_path')
    op.drop_column('asset_categories', 'default_thumbnail_path')
    # ### end Alembic commands ###
