"""updateded shot sequecence schema

Revision ID: 59037e79c372
Revises: bd67c4e156f8
Create Date: 2025-12-01 15:28:28.048113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59037e79c372'
down_revision: Union[str, Sequence[str], None] = 'bd67c4e156f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shots', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('shots', sa.Column('cut_in', sa.Float(), nullable=True))
    op.add_column('shots', sa.Column('cut_out', sa.Float(), nullable=True))
    op.add_column('shots', sa.Column('cut_duration', sa.Float(), nullable=True))
    op.add_column('shots', sa.Column('head_in', sa.Float(), nullable=True))
    op.add_column('shots', sa.Column('head_out', sa.Float(), nullable=True))
    op.add_column('shots', sa.Column('head_duration', sa.Float(), nullable=True))
    op.add_column('shots', sa.Column('tail_in', sa.Float(), nullable=True))
    op.add_column('shots', sa.Column('tail_out', sa.Float(), nullable=True))
    op.add_column('shots', sa.Column('tail_duration', sa.Float(), nullable=True))
    op.add_column('shots', sa.Column('fps', sa.Float(), nullable=True))
    op.add_column('shots', sa.Column('cut_order', sa.Integer(), nullable=True))
    op.add_column('shots', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('shots', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.alter_column('shots', 'sequence_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('uq_shot_code_per_project'), 'shots', type_='unique')
    op.drop_constraint(op.f('shots_sequence_id_fkey'), 'shots', type_='foreignkey')
    op.create_foreign_key(None, 'shots', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'shots', 'sequences', ['sequence_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shots', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('shots', 'sort_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shots', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shots', type_='foreignkey')
    op.drop_constraint(None, 'shots', type_='foreignkey')
    op.drop_constraint(None, 'shots', type_='foreignkey')
    op.create_foreign_key(op.f('shots_sequence_id_fkey'), 'shots', 'sequences', ['sequence_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('uq_shot_code_per_project'), 'shots', ['project_id', 'code'], postgresql_nulls_not_distinct=False)
    op.alter_column('shots', 'sequence_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('shots', 'updated_by')
    op.drop_column('shots', 'created_by')
    op.drop_column('shots', 'cut_order')
    op.drop_column('shots', 'fps')
    op.drop_column('shots', 'tail_duration')
    op.drop_column('shots', 'tail_out')
    op.drop_column('shots', 'tail_in')
    op.drop_column('shots', 'head_duration')
    op.drop_column('shots', 'head_out')
    op.drop_column('shots', 'head_in')
    op.drop_column('shots', 'cut_duration')
    op.drop_column('shots', 'cut_out')
    op.drop_column('shots', 'cut_in')
    op.drop_column('shots', 'description')
    # ### end Alembic commands ###
