"""updated product schema

Revision ID: 594262184baf
Revises: 0b9e5af4b889
Create Date: 2025-11-26 11:50:44.629454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594262184baf'
down_revision: Union[str, Sequence[str], None] = '0b9e5af4b889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_assets_bb3')
    op.add_column('products', sa.Column('owner_kind', sa.String(), nullable=False))
    op.add_column('products', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.add_column('products', sa.Column('created_by', sa.UUID(), nullable=False))
    op.create_index('idx_products_owner', 'products', ['owner_kind', 'owner_id'], unique=False)
    op.create_index('idx_products_project', 'products', ['project_id'], unique=False)
    op.create_unique_constraint('uniq_products_owner_type', 'products', ['project_id', 'owner_kind', 'owner_id', 'product_type_id'])
    op.drop_constraint(op.f('products_asset_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_task_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_shot_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_user_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.drop_column('products', 'asset_id')
    op.drop_column('products', 'user_id')
    op.drop_column('products', 'task_id')
    op.drop_column('products', 'name')
    op.drop_column('products', 'shot_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('shot_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_user_id_fkey'), 'products', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('products_shot_id_fkey'), 'products', 'shots', ['shot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('products_task_id_fkey'), 'products', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('products_asset_id_fkey'), 'products', 'assets', ['asset_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uniq_products_owner_type', 'products', type_='unique')
    op.drop_index('idx_products_project', table_name='products')
    op.drop_index('idx_products_owner', table_name='products')
    op.drop_column('products', 'created_by')
    op.drop_column('products', 'owner_id')
    op.drop_column('products', 'owner_kind')
    op.create_table('import_assets_bb3',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mvl_client_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('client_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('asset_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('project', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('column11', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
