"""make asset type global

Revision ID: 6a06607b3c55
Revises: 1f733c0f4811
Create Date: 2025-11-20 17:21:47.921844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a06607b3c55'
down_revision: Union[str, Sequence[str], None] = '1f733c0f4811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_access_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_group_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['access_group_id'], ['access_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'access_group_id', name='uq_user_group')
    )
    op.add_column('asset_categories', sa.Column('asset_type_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_asset_category_project_name'), 'asset_categories', type_='unique')
    op.create_unique_constraint('uq_asset_category_type_name', 'asset_categories', ['asset_type_id', 'name'])
    op.drop_constraint(op.f('asset_categories_project_id_fkey'), 'asset_categories', type_='foreignkey')
    op.create_foreign_key(None, 'asset_categories', 'asset_types', ['asset_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('asset_categories', 'project_id')
    op.drop_constraint(op.f('uq_asset_type_project_name'), 'asset_types', type_='unique')
    op.drop_constraint(op.f('asset_types_asset_category_id_fkey'), 'asset_types', type_='foreignkey')
    op.drop_constraint(op.f('asset_types_project_id_fkey'), 'asset_types', type_='foreignkey')
    op.drop_column('asset_types', 'asset_category_id')
    op.drop_column('asset_types', 'project_id')
    op.drop_constraint(op.f('uq_project_access_group'), 'project_access_groups', type_='unique')
    op.create_unique_constraint('uq_project_group', 'project_access_groups', ['project_id', 'access_group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_group', 'project_access_groups', type_='unique')
    op.create_unique_constraint(op.f('uq_project_access_group'), 'project_access_groups', ['project_id', 'access_group_id'], postgresql_nulls_not_distinct=False)
    op.add_column('asset_types', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('asset_types', sa.Column('asset_category_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('asset_types_project_id_fkey'), 'asset_types', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('asset_types_asset_category_id_fkey'), 'asset_types', 'asset_categories', ['asset_category_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_asset_type_project_name'), 'asset_types', ['project_id', 'name'], postgresql_nulls_not_distinct=False)
    op.add_column('asset_categories', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'asset_categories', type_='foreignkey')
    op.create_foreign_key(op.f('asset_categories_project_id_fkey'), 'asset_categories', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_asset_category_type_name', 'asset_categories', type_='unique')
    op.create_unique_constraint(op.f('uq_asset_category_project_name'), 'asset_categories', ['project_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_column('asset_categories', 'asset_type_id')
    op.drop_table('user_access_groups')
    # ### end Alembic commands ###
