"""updateded shot sequecence schema

Revision ID: 6f772645c3c1
Revises: 59037e79c372
Create Date: 2025-12-01 15:35:49.596232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f772645c3c1'
down_revision: Union[str, Sequence[str], None] = '59037e79c372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_shot_links',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('shot_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'shot_id', name='asset_shot_links_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_shot_links')
    # ### end Alembic commands ###
