"""updated projects table

Revision ID: b8fa1b12e9ba
Revises: 6a06607b3c55
Create Date: 2025-11-20 17:38:20.398398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8fa1b12e9ba'
down_revision: Union[str, Sequence[str], None] = '6a06607b3c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('type', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('status', sa.String(), nullable=False))
    op.add_column('projects', sa.Column('archived', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('thumbnail', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('updated_by', sa.String(), nullable=True))
    op.drop_column('projects', 'library')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('library', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('projects', 'updated_by')
    op.drop_column('projects', 'thumbnail')
    op.drop_column('projects', 'archived')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'type')
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
