"""updateded shot sequecence schema

Revision ID: bd67c4e156f8
Revises: 594262184baf
Create Date: 2025-12-01 15:03:36.735670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd67c4e156f8'
down_revision: Union[str, Sequence[str], None] = '594262184baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:


    op.execute(
        "UPDATE users SET attrib = '{}'::jsonb WHERE attrib IS NULL"
    )

    op.execute(
        "UPDATE users SET data = '{}'::jsonb WHERE data IS NULL"
    )
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_assets_bb3')
    op.add_column('sequences', sa.Column('status', sa.Text(), nullable=False))
    op.add_column('sequences', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('sequences', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('sequences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_sequence_project_code'), 'sequences', type_='unique')
    op.create_unique_constraint('uq_sequence_code_per_project', 'sequences', ['project_id', 'code'])
    op.add_column('shots', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.add_column('shots', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('shots', 'sequence_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('shots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint('uq_shot_code_per_project', 'shots', ['project_id', 'code'])
    op.drop_constraint(op.f('shots_sequence_id_fkey'), 'shots', type_='foreignkey')
    op.create_foreign_key(None, 'shots', 'sequences', ['sequence_id'], ['id'], ondelete='SET NULL')
    op.drop_column('shots', 'cutin')
    op.drop_column('shots', 'tailout')
    op.drop_column('shots', 'headin')
    op.drop_column('shots', 'cutout')
    op.alter_column('users', 'attrib',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('users', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('users', 'attrib',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.add_column('shots', sa.Column('cutout', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('shots', sa.Column('headin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('shots', sa.Column('tailout', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('shots', sa.Column('cutin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shots', type_='foreignkey')
    op.create_foreign_key(op.f('shots_sequence_id_fkey'), 'shots', 'sequences', ['sequence_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_shot_code_per_project', 'shots', type_='unique')
    op.alter_column('shots', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('shots', 'sequence_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('shots', 'updated_at')
    op.drop_column('shots', 'sort_order')
    op.drop_constraint('uq_sequence_code_per_project', 'sequences', type_='unique')
    op.create_unique_constraint(op.f('uq_sequence_project_code'), 'sequences', ['project_id', 'code'], postgresql_nulls_not_distinct=False)
    op.alter_column('sequences', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('sequences', 'updated_at')
    op.drop_column('sequences', 'meta')
    op.drop_column('sequences', 'status')
    op.create_table('import_assets_bb3',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MVL Client Name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Client Name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Asset Name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('project', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('column11', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
