"""Added product id to tasks

Revision ID: ec9e097d9812
Revises: ff16ca7f9fcb
Create Date: 2025-12-17 12:02:43.531317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec9e097d9812'
down_revision: Union[str, Sequence[str], None] = 'ff16ca7f9fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gen63_sequence_info')
    op.drop_table('gen63_shot_info')
    op.drop_constraint(op.f('uq_user_access_group'), 'access_group_members', type_='unique')
    op.create_unique_constraint('access_user_group', 'access_group_members', ['user_kc_id', 'access_group_id'])
    op.add_column('tasks', sa.Column('product_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'product_id')
    op.drop_constraint('access_user_group', 'access_group_members', type_='unique')
    op.create_unique_constraint(op.f('uq_user_access_group'), 'access_group_members', ['user_kc_id', 'access_group_id'], postgresql_nulls_not_distinct=False)
    op.create_table('gen63_shot_info',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Client Name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('MVL Client Name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Shot Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Sequence', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Cut In', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Cut Order', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Cut Out', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Head In', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Clip Number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('column17', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('gen63_sequence_info',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Sequence Name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('MVL Client Name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('shots', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('project', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('column9', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
