"""update access group

Revision ID: ff16ca7f9fcb
Revises: 1ad9d07b93d0
Create Date: 2025-12-15 15:29:16.116226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff16ca7f9fcb'
down_revision: Union[str, Sequence[str], None] = '1ad9d07b93d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_groups'), 'access_group_members', type_='unique')
    op.create_unique_constraint('uq_user_access_group', 'access_group_members', ['user_kc_id', 'access_group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_group', 'access_group_members', type_='unique')
    op.create_unique_constraint(op.f('uq_user_groups'), 'access_group_members', ['user_kc_id', 'access_group_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
